import os
import time
import random
anim=""
pokedex=[""]
loop=True
anim=("")
rarity=("")

def clear():
    os.system('cls' if os.name == 'nt' else 'clear')
noinput=("")
golden=("Pikachu GOLD")
fullart = [
    "Pikachu(full art)","Pidgey(full art)","Mew(full art)","Rapidash(full art)","Bulbasaur(full art)","Charmander(full art)","Mr Mime (full art)", "Gyrados (full art)","Exeguttor"]
legendary = [
    "Articuno", "Zapdos", "Moltres", 
    "Mewtwo", "Mew"
]
very_rare = [
    "Charizard", "Venusaur", "Blastoise", 
    "Alakazam", "Gengar", "Gyarados", 
    "Dragonite", "Nidoqueen", "Nidoking", 
    "Machamp", "Exeggutor", "Arcanine"
]
rare = [
    "Tauros", "Lapras", "Scyther", 
    "Porygon", "Jynx", "Electabuzz", 
    "Farfetch'd", "Mr. Mime", "Aerodactyl", 
    "Hitmonlee", "Hitmonchan", "Chansey", 
    "Tangela", "Kangaskhan", "Pinsir"
]
uncommon = [
    "Butterfree", "Beedrill", "Pidgeot", 
    "Raichu", "Sandslash", "Clefable", 
    "Vileplume", "Victreebel", "Poliwrath", 
    "Golem", "Rapidash", "Slowbro", 
    "Magneton", "Dewgong", "Muk", 
    "Cloyster", "Hypno", "Weezing", 
    "Rhydon", "Seadra", "Starmie"
]
common = [
    "Pidgey", "Rattata", "Spearow", 
    "Caterpie", "Weedle", "Zubat", 
    "Magikarp", "Pikachu", "Geodude", 
    "Oddish", "Bellsprout", "Paras", 
    "Venonat", "Diglett", "Meowth", 
    "Psyduck", "Poliwag", "Machop", 
    "Tentacool", "Gastly", "Krabby", 
    "Horsea", "Goldeen", "Staryu", 
    "Doduo", "Shellder", "Drowzee", 
    "Voltorb", "Koffing", "Rhyhorn"
]
packet=input("""
                 
 _________  ________  ________          ________  ___    ___ 
|\___   ___\\   ____\|\   ____\        |\   __  \|\  \  /  /|   Version 1.0.0 
\|___ \  \_\ \  \___|\ \  \___|        \ \  \|\  \ \  \/  / |
     \ \  \ \ \  \    \ \  \  ___       \ \   ____\ \    / /      
      \ \  \ \ \  \____\ \  \|\  \       \ \  \___|\/  /  /      
       \ \__\ \ \_______\ \_______\       \ \__\ __/  / /
        \|__|  \|_______|\|_______|        \|__||\___/ /            
                                                \|___|/                                                   

                                                                                      
                            [ENTER] to START""")
clear()
while loop == True:
    print("██L██L██L██L██L██L         █████████████████████████          ")
    print("██L██L██L██L██L██L         ████                   ████        ")
    print("██████████████████         ████                     ████      ")
    print("██              ██         ████        (-0-)          ████    ")
    print("██              ██         ████                       ████    ")
    print("██     (-0-)    ██         ████       pokedex         ████    ")
    print("██   TCG PACKET ██         ████                       ████    ")
    print("██   Vol. 1     ██         ███████████████████████████████    ")
    print("██              ██         ████                       ████    ")
    print("██  popular151] ██         ████                       ████    ")
    print("██              ██         ████                       ████    ")
    print("██████████████████         ████                       ████    ")
    print("██████████████████         ███████████████████████████████    ")
    print("")
    packet=input("press enter again to open:")
    clear()
    print("██L██L██L██L██L██L")
    print("██L██L██L██L██L██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("██ ")
    print("██L██L██L██L██L██L")
    print("  L██L██L██L██L██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("██L")
    print("██L██L██L██L██L██L")
    print("   ██L██L██L██L██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("██L██")
    print("██L██L██L██L██L██L")
    print("     L██L██L██L██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("██L██L")
    print("  L██L██L██L██L██L")
    print("      ██L██L██L██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("██L██L██")
    print("   ██L██L██L██L██L")
    print("        L██L██L██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.2)
    clear()
    print("██L██L██L")
    print("     L██L██L██L██L")
    print("         ██L██L██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("  L██L██L")
    print("     L██L██L██L██L")
    print("         ██L██L██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("   ██L██L██")
    print("     L██L██L██L██L")
    print("           L██L██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("██L██L")
    print("██L██L██")
    print("      ██L██L██")
    print("        L██L██L██L")
    print("              L██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("      ██L██L██")
    print("        L██L██L██L")
    print("              L██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.2)
    clear()
    print("         ██L██")
    print("            ██L██L")
    print("              L██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("           L██L")
    print("              L██L")
    print("               ██L")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("              L██L")
    print("               ██L")
    print("                  ")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("               ██L")
    print("                  ")
    print("                  ")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("                  ")
    print("                  ")
    print("                  ")
    print("██████████████████")
    print("██              ██")
    print("██              ██")
    print("██     (-0-)    ██")
    print("██   TCG PACKET ██")
    print("██   Vol. 1     ██")
    print("██              ██")
    print("██  popular151] ██")
    print("██              ██")
    print("██████████████████")
    time.sleep(0.1)
    clear()
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    print("████████████████████████████████████")
    time.sleep(0.5)
    clear()
    for i in range(5):
        rng=random.randint(1,100)
        if rng < 51:
            rcard=common[random.randint(0,29)]
            rarity=("✦")
        else:
            rng=random.randint(1,100)
            if rng < 81:
                rcard=rare[random.randint(0,14)]
                rarity=("✦✦")
            else:
                rng=random.randint(1,100)
                if rng < 81:
                    rcard=very_rare[random.randint(0,11)]
                    anim=("vrare")
                    rarity=("✦✦✦")
                else:
                    ng=random.randint(1,20)
                    if rng < 11:
                        rcard=legendary[random.randint(0,4)]
                        anim=("legend")
                        rarity=("☆")
                    elif rng == 20:
                        rcard=golden
                        anim=("gold")
                        rarity=("★")
                    else:
                        rcard=fullart[random.randint(0,4)]
                        anim=("fullart")
                        rarity=("☆") 
        if anim == ("vrare"):
            print("You got")
            time.sleep(0.5)
            clear()
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("███████  ███████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("███████  ███████")
            print("██████    ██████")
            print("███████  ███████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("████████████████")
            print("███████  ███████")
            print("██████    ██████")
            print("█████      █████")
            print("██████    ██████")
            print("███████  ███████")
            print("████████████████")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("███████  ███████")
            print("██████    ██████")
            print("█████      █████")
            print("████        ████")
            print("█████      █████")
            print("██████    ██████")
            print("███████  ███████")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("███████  ███████")
            print("██████    ██████")
            print("█████      █████")
            print("████        ████")
            print("███          ███")
            print("████        ████")
            print("█████      █████")
            print("██████    ██████")
            print("███████  ███████")
            time.sleep(0.2)
            clear()
            print("██████    ██████")
            print("█████      █████")
            print("████        ████")
            print("███          ███")
            print("██            ██")
            print("███          ███")
            print("████        ████")
            print("█████      █████")
            print("██████    ██████")
            time.sleep(0.2)
            clear()
            print("█████      █████")
            print("████        ████")
            print("███          ███")
            print("██            ██")
            print("█              █")
            print("██            ██")
            print("███          ███")
            print("████        ████")
            print("█████      █████")
            time.sleep(0.2)
            clear()
            print("█████      █████")
            print("████        ████")
            print("███          ███")
            print("██   SUPER    ██")
            print("█     RARE     █")
            print("██            ██")
            print("███          ███")
            print("████        ████")
            print("█████      █████")
            time.sleep(1)
            clear()
            print("█████      █████")
            print("████        ████")
            print("███          ███")
            print("█              █")
            print("   ", rcard)
            print("█      ✦✦✦     █")
            print("███          ███")
            print("████        ████")
            print("█████      █████")
            time.sleep(1)
            clear()
            print("You got", rcard)
            print("Rarity:", rarity)
        elif anim == ("legend"):
            print("You got")
            time.sleep(0.5)
            clear()
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("████████████████")
            print("████████████████")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████  ██")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("█     ████     █")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████      ██")
            print("██  ████████████")
            print("       ██       ")
            print("████████████  ██")
            print("██      ████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████      ██")
            print("██  ████████████")
            print("                ")
            print("████████████  ██")
            print("██      ████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████      ██")
            print("██  ████████████")
            print("    Legendary   ")
            print("████████████  ██")
            print("██      ████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(1)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████   ☆  ██")
            print("██  ████████████")
            print("   ", rcard)
            print("████████████  ██")
            print("██   ☆  ████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(1)
            clear()
            print("You got", rcard)
            print("Rarity:", rarity)
        elif anim == ("fullart"):
            print("You got")
            time.sleep(0.5)
            clear()
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("████████████████")
            print("████████████████")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████  ██")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████  ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██   ███████████")
            print("██  ████████████")
            print("██  ████████████")
            print("██  ████████████")
            print("█     ████     █")
            print("████████████  ██")
            print("████████████  ██")
            print("███████████   ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("██   ███████████")
            print("██  ████████████")
            print("██  ████      ██")
            print("██  ████████████")
            print("       ██       ")
            print("████████████  ██")
            print("██      ████  ██")
            print("███████████   ██")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("███  ███████████")
            print("██   ███████████")
            print("██  ████████████")
            print("██  ████      ██")
            print("██  ████████████")
            print("                ")
            print("████████████  ██")
            print("██      ████  ██")
            print("███████████   ██")
            print("███████████  ███")
            time.sleep(0.2)
            clear()
            print("████          ██")
            print("██    ██████████")
            print("██  ████████████")
            print("██  ████      ██")
            print("██  ████████████")
            print("    Full Art   ")
            print("████████████  ██")
            print("██      ████  ██")
            print("██████████    ██")
            print("██          ████")
            time.sleep(1)
            clear()
            print("███           ██")
            print("██    ██████████")
            print("██  ████████████")
            print("██  ████  [☆] ██")
            print("██  ████████████")
            print(" ", rcard)
            print("████████████  ██")
            print("██  [☆]  ███  ██")
            print("██████████    ██")
            print("██           ███")
        elif anim == ("golden"):
            print("You got")
            time.sleep(0.5)
            clear()
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("███████**███████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("████████████████")
            print("████████████████")
            print("███████**███████")
            print("██████****██████")
            print("███████**███████")
            print("████████████████")
            print("████████████████")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("████████████████")
            print("███████**███████")
            print("██████****██████")
            print("█████******█████")
            print("██████****██████")
            print("███████**███████")
            print("████████████████")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("████████████████")
            print("███████**███████")
            print("██████****██████")
            print("█████******█████")
            print("████********████")
            print("█████******█████")
            print("██████****██████")
            print("███████**███████")
            print("████████████████")
            time.sleep(0.2)
            clear()
            print("███████**███████")
            print("██████****██████")
            print("█████******█████")
            print("████********████")
            print("███**********███")
            print("████********████")
            print("█████******█████")
            print("██████****██████")
            print("███████**███████")
            time.sleep(0.2)
            clear()
            print("██████****██████")
            print("█████******█████")
            print("████********████")
            print("███**********███")
            print("██************██")
            print("███**********███")
            print("████********████")
            print("█████******█████")
            print("██████****██████")
            time.sleep(0.2)
            clear()
            print("█████******█████")
            print("████********████")
            print("███**********███")
            print("██************██")
            print("█**************█")
            print("██************██")
            print("███**********███")
            print("████********████")
            print("█████******█████")
            time.sleep(0.2)
            clear()
            print("█████******█████")
            print("████********████")
            print("███**********███")
            print("██************██")
            print("█****GOLDEN****█")
            print("██************██")
            print("███**********███")
            print("████********████")
            print("█████******█████")
            time.sleep(0.2)
            clear()
            print("█████★★★★★★█████")
            print("████★★★★★★★★████")
            print("███★★★★★★★★★★███")
            print("██★★★★★★★★★★★★██")
            print("█★★★★GOLDEN★★★★█")
            print("██★★★★★★★★★★★★██")
            print("███★★★★★★★★★★███")
            print("████★★★★★★★★████")
            print("█████★★★★★★█████")
            time.sleep(0.2)
            print("█████******█████")
            print("████********████")
            print("███**********███")
            print("██************██")
            print("█****GOLDEN****█")
            print("██************██")
            print("███**********███")
            print("████********████")
            print("█████******█████")
            time.sleep(0.2)
            clear()
            print("█████★★★★★★█████")
            print("████★★★★★★★★████")
            print("███★★★★★★★★★★███")
            print("██★★★★★★★★★★★★██")
            print("█★★★★GOLDEN★★★★█")
            print("██★★★★★★★★★★★★██")
            print("███★★★★★★★★★★███")
            print("████★★★★★★★★████")
            print("█████★★★★★★█████")
            time.sleep(0.2)
            clear()
            print("█████******█████")
            print("████********████")
            print("███**********███")
            print("██************██")
            print("█****GOLDEN****█")
            print("██************██")
            print("███**********███")
            print("████********████")
            print("█████******█████")
            time.sleep(0.2)
            clear()
            print("█████★★★★★★█████")
            print("████★★★★★★★★████")
            print("███★★★★★★★★★★███")
            print("██★★★★★★★★★★★★██")
            print("█★★★★GOLDEN★★★★█")
            print("██★★★★★★★★★★★★██")
            print("███★★★★★★★★★★███")
            print("████★★★★★★★★████")
            print("█████★★★★★★█████")
            time.sleep(0.2)
            clear()
            print("█████******█████")
            print("████********████")
            print("███**********███")
            print("██************██")
            print("█***CONGRATS***█")
            print("██************██")
            print("███**********███")
            print("████********████")
            print("█████******█████")
            time.sleep(0.2)
            clear()
            print("█████★★★★★★█████")
            print("████★★★★★★★★████")
            print("███★★★★★★★★★★███")
            print("██★★★★★★★★★★★★██")
            print("█★★★CONGRATS★★★█")
            print("██★★★★★★★★★★★★██")
            print("███★★★★★★★★★★███")
            print("████★★★★★★★★████")
            print("█████★★★★★★█████")
            time.sleep(0.2)
            clear()
            print("█████******█████")
            print("████********████")
            print("███**********███")
            print("██************██")
            print("█***CONGRATS***█")
            print("██************██")
            print("███**********███")
            print("████********████")
            print("█████******█████")
            time.sleep(0.2)
            clear()
            print("█████★★★★★★█████")
            print("████★★★★★★★★████")
            print("███★★★★★★★★★★███")
            print("██★★★★★★★★★★★★██")
            print("█★★★CONGRATS★★★█")
            print("██★★★★★★★★★★★★██")
            print("███★★★★★★★★★★███")
            print("████★★★★★★★★████")
            print("█████★★★★★★█████")
            time.sleep(0.2)
            clear()
            print("█████★★★★★★█████")
            print("████★★★★★★★★████")
            print("███★★★★★★★★★★███")
            print("██★★★★★★★★★★★★██")
            print("█★★★★GOLDEN★★★★█")
            print("██★★★PIKACHU★★██")
            print("███★★★★★★★★★★███")
            print("████★★★★★★★★████")
            print("█████★★★★★★█████")
            time.sleep(1)
            clear()
            print("You got", rcard)
            print("Rarity:", rarity)
        else:
            print("You got")
            time.sleep(0.5)
            clear()
            print("You got", rcard)
            print("Rarity:", rarity)
        if i < 4:
            nothing = input("Press [Enter] to see next card")
            anim=("")
            clear()
        elif i == 4:
            nothing=input("Press [Enter] to return to menu")
    clear()
        